version: "3.9"

services:
  app:
    container_name: announcement
    build: .
    ports:
      - "3069:3000"
    environment:
      - NODE_ENV=production
    restart: always

#
#networks:
#  default:
#    name: dnd
#    external: true
